### ISSUE TITLE
Compiling the project does not get the Castle.Windsor nuget

### ISSUE THREAD

**Issue by satyajit-behera** [padzikm/CompositeUI#2]
Compiling the project gives the following error:

The type or namespace name 'WindsorContainer' could not be found (are you missing a using directive or an assembly reference?)  

Looks like version 3.3.0 is not available in the nuget.org server.

**Comment by brunobertechini** [comment]
Just downloaded solution and the only problem I got was that packages were commited to git. After removing all packages manually and restoring build succeeded.

Submitted PR #4 for these small changes

Bruno
