### ISSUE TITLE
Is this source code to have any samples?

### ISSUE THREAD

**Issue by brunobertechini** [padzikm/CompositeUI#3]
I have downloaded the source code (forked/cloned from github) and make it build with some caveats (I can share them later).

Im trying to find something visual like pages/tests/urls to be able to use the application but I cant get my hands to work...

Are there any url to be accessed after the app is launched ?

Bruno

**Comment by brunobertechini** [comment]
Anyone alive ?

**Comment by padzikm** [comment]
Hi, urls are standard mvc routes - {controller}/{action} or {area}/{controller}/{action} - look at controllers or areas folders in Web project to see exact names.
For example:
ProductDrafts/Index
ProductDrafts/IndexTable
ProductDrafts/IndexDiff
PubSubCache/Communication
PubSubCache/Networking
Test/AddCustomer
TestArea/Test/AddCustomer
